anatawa12/AvatarOptimizer

Editor/MergeSkinnedMeshEditor.cs, README.md
=> Improve merge skinned mesh documentation

Editor/Migration.meta, Editor/Migration/Migration.cs, Editor/Migration/Migration.cs.meta, Editor/Migration/PrereleaseStateDetector.cs, Editor/Migration/PrereleaseStateDetector.cs.meta
This is required for v0.2 release
=> chore: Add support for feature Migration

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs, Editor/Processors/SkinnedMeshes/MeshInfo2.cs
=> SkinnedMeshRenderers without bones

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/ClearEndpointPositionEditor.cs, Editor/FreezeBlendShapeEditor.cs, Editor/MakeChildrenEditor.cs, Editor/MergeBoneEditor.cs, Editor/MergePhysBoneEditor.cs, Editor/MergeSkinnedMeshEditor.cs, Editor/MergeToonLitMaterialEditor.cs, Editor/RemoveMeshInBoxEditor.cs, Editor/SaveVersionDrawer.cs, Editor/SaveVersionDrawer.cs.meta
SaveVersion is internal info but will always generate diff on prefabs so I show the save version on editor with disabled.
=> feat: show save version on editor

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/MergeSkinnedMeshEditor.cs, Editor/ToggleLeftDrawer.cs, Editor/ToggleLeftDrawer.cs.meta, Runtime/MergeSkinnedMesh.cs, Runtime/ToggleLeftAttribute.cs, Runtime/ToggleLeftAttribute.cs.meta
=> Remove Empty Renderer Object is gone on editor

Editor/Processors/EditSkinnedMeshComponentProcessor.cs, Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs, Editor/Processors/SkinnedMeshes/MeshInfo2.cs, Editor/Processors/SkinnedMeshes/RemoveMeshInBoxProcessor.cs
=> fix: breaking InvariantContract

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/MergePhysBoneEditor.cs, Editor/Processors/MergePhysBoneProcessor.cs, Editor/Utils.cs, Editor/com.anatawa12.avatar-optimizer.editor.asmdef, Localization/en.po, Runtime/MergePhysBone.cs
=> feat: support for 3.1.12 / later

README.md
- vrchat-community/creator-companion#223
- vrchat-community/template-package#4
=> docs(readme): add vcc://vpm/addRepo link

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/MergePhysBoneEditor.cs, Editor/Migration/Migration.cs, Editor/Processors/MergePhysBoneProcessor.cs, Localization/en.po, Runtime/MergePhysBone.cs
=> remove Root transform option

CHANGELOG-PRERELEASE.md, Editor/PreventRemoveAvatarEditorOnly.cs, Editor/PreventRemoveAvatarEditorOnly.cs.meta
https://misskey.niri.la/notes/9e0vscm4vk
=> fix: components are already removed at the time OptimizerProcessor

.github/workflows/release.yml, README.md
This includes generating installer for each version using web api
Closes #44
=> Use vpai web api

.docs/config.toml, .docs/content/_index.ja.md, .docs/content/_index.md
=> Hugo docs improvements

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/ManualBake.cs, Editor/ManualBake.cs.meta, Editor/OptimizerProcessor.cs, Editor/OptimizerSession.cs, Editor/Utils.cs, Internal/ErrorReporter/Editor/BuildReport.cs
=> feat: add Manual Bake Avatar

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/ObjectMapping.cs, Editor/Processors/ApplyObjectMapping.cs
=> fix: objects became none

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/ObjectMapping.cs, Editor/Utils.cs
=> Error with gameobject with same name

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Localization/ja.po, Localization/ja.po.meta
=> feat: japanese localization

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/ObjectMapping.cs
=> fix: error with animator at non-root

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Runtime/MergePhysBone.cs
=> fix: error if we copied MergePhysBone

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Internal/ErrorReporter/Editor/ErrorReportingInitializerProcessor.cs
=> fix: error is not cleared on build

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/MergePhysBoneEditor.cs
=> Merge physbone editor bugs

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/SkinnedMeshes/MergeToonLitMaterialProcessor.cs
=> fix: error in MergeToonLit

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs, Test~/ObjectMappingTest.cs
=> Remove enabled property for merge source skinned mesh

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Runtime/AvatarTagComponent.cs
=> components may not applied on play

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Internal/PrefabSafeSet/Editor/EditorUtil.PrefabModification.cs, Internal/PrefabSafeSet/Editor/EditorUtil.Root.cs, Internal/PrefabSafeSet/Editor/EditorUtil.cs, Internal/PrefabSafeSet/Editor/PrefabSafeSetEditor.cs
=> Prefab safe set editor improvements

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Internal/PrefabSafeSet/Editor/EditorUtil.PrefabModification.cs
_prefabLayers.arraySize is no longer _nestCount
=> fix(prefab-safe-set): prefab modifications on latest layer are invisible on inspector

.docs/content/docs/tutorial/basic-usage/index.ja.md
=> docs: add reference to actual performance window

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Internal/ApplyOnPlay/Editor/RemoveEditorOnlyOnPlay.cs
=> chore: don't remove whole avatar with EditorOnly tag

.docs/content/docs/reference/merge-skinned-mesh/index.ja.md, .docs/content/docs/reference/merge-skinned-mesh/index.md, .docs/content/docs/tutorial/basic-usage/index.ja.md, .docs/content/docs/tutorial/basic-usage/index.md, CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/EditSkinnedMeshComponentProcessor.cs, Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs, Editor/Processors/SkinnedMeshes/MeshInfo2.cs, Editor/Utils.cs
=> Automatic bounds computation in MergeSkinnedMesh

.docs/content/docs/reference/merge-bone/index.ja.md
=> fix(docs): merge-bone index.ja.md

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/ObjectMapping/ObjectMapping.cs, Editor/Processors/ApplyObjectMapping.cs
=> fix: animating Behaviour.m_Enabled not working

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Runtime/AutomaticConfiguration.cs, Runtime/ClearEndpointPosition.cs, Runtime/FreezeBlendShape.cs, Runtime/MakeChildren.cs, Runtime/MergeBone.cs, Runtime/MergePhysBone.cs, Runtime/MergeSkinnedMesh.cs, Runtime/MergeToonLitMaterial.cs, Runtime/RemoveMeshByBlendShape.cs, Runtime/RemoveMeshInBox.cs, Runtime/UnusedBonesByReferencesTool.cs, Test~/AddComponentMenuTest.cs
=> chore: add AAO prefix to component names

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/MakeChildrenEditor.cs, Editor/OptimizerProcessor.cs, Editor/Processors/MakeChildrenProcessor.cs, Localization/en.po, Localization/ja.po, Runtime/MakeChildren.cs
=> feat: early processing MakeChildren

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Internal/ApplyOnPlay/Editor/ApplyOnPlayCaller.cs, Internal/ApplyOnPlay/Runtime/GlobalActivator.cs, Internal/ApplyOnPlay/Runtime/GlobalActivator.cs.meta
With enter playmode option off, Awake can be before IProcessSceneWithReport
Fixes #281
=> fix: Apply On Play may executed after Av3Emu

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/EditSkinnedMeshComponentUtil.cs
=> Early circular dependency detection

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/PreventRemoveAvatarEditorOnly.cs
fix https://misskey.niri.la/notes/9ik8ip4bm2
=> fix: Network IDs us not assigned for newly created PBs

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/AutomaticConfiguration/AutomaticConfigurationProcessor.CollectUsages.cs, Editor/Utils.cs
=> fix(trace-and-optimize): something are not considered

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/SkinnedMeshes/MeshInfo2.cs
=> fix: MaterialSlot and SubMesh count mismatch

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/AutomaticConfiguration/AutomaticConfigurationProcessor.FindUnusedObjects.cs
=> fix: children of IsActive animated object is not considered

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/SkinnedMeshes/MeshInfo2.cs
=> fix(MeshInfo2): Multi Passs Rendering not supported error doesn't have location info

Localization/ja.po
=> chore: Japanese translation of weight mismatch warning

.docs/content/docs/component-kind/avatar-global-components/index.ja.md, .docs/content/docs/component-kind/edit-skinned-mesh-components/index.ja.md
https://misskey.niri.la/notes/9in53d0za4
=> docs: fix link from component kind to components

.docs/content/docs/tutorial/basic-usage/index.ja.md
=> docs(ja): マージ to 統合

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Math.meta, Editor/Math/Matrix4x4.cs, Editor/Math/Matrix4x4.cs.meta, Editor/Processors/EditSkinnedMeshComponentProcessor.cs, Editor/Processors/MergeBoneProcessor.cs, Editor/Processors/SkinnedMeshes/MeshInfo2.cs, Editor/Utils.cs
=> Merge bone for non restpose

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Runtime/ClearEndpointPosition.cs, Runtime/FreezeBlendShape.cs, Runtime/MakeChildren.cs, Runtime/MergeBone.cs, Runtime/MergePhysBone.cs, Runtime/MergeSkinnedMesh.cs, Runtime/MergeToonLitMaterial.cs, Runtime/RemoveMeshByBlendShape.cs, Runtime/RemoveMeshInBox.cs, Runtime/TraceAndOptimize.cs, Runtime/UnusedBonesByReferencesTool.cs, Test~/ComponentSettingsTest.cs
=> chore: add link to Help Page for each Component

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/SkinnedMeshes/MeshInfo2.cs
Closes #338 
結局SubMeshを複製しといて、出力段でmergeにした
=> Support multi pass rendering

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/OptimizerSession.cs, Editor/Processors/EditSkinnedMeshComponentProcessor.cs, Editor/Processors/SkinnedMeshes/MeshInfo2.cs
=> chore: Error if there are non-Readable Mesh

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/ClearEndpointPositionEditor.cs, Editor/Processors/ClearEndpointPositionProcessor.cs
Fixes #388 
In addition, small bugfix.
=> Undo clear endpoint position

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/OptimizerProcessor.cs
=> chore: make human readable error when we found missing script component

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/ExternalLibraryAccessor.cs, Editor/ExternalLibraryAccessor.cs.meta, Editor/OptimizerProcessor.cs, Editor/Processors/TraceAndOptimize/AnimatorParser.cs, Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs, Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs.meta, Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs, Editor/Processors/TraceAndOptimize/ModificationsContainers.cs, Editor/Processors/TraceAndOptimize/TraceAndOptimizeProcessor.cs, Editor/com.anatawa12.avatar-optimizer.editor.asmdef
Implements part of #291
Closes #292
=> Better Remove Unused Objects: GC Objects

CHANGELOG-PRERELEASE.md, Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs, Localization/en.po, Localization/ja.po
=> fix: warning message of Unknown Type is not localized

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Localization/AssemblyInfo.cs, Localization/AssemblyInfo.cs.meta, Localization/com.anatawa12.avatar-optimizer.localization.asmdef, Localization/com.anatawa12.avatar-optimizer.localization.asmdef.meta
=> fix: Unity 2022 crash workaround

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/MergeBoneProcessor.cs, Internal/ErrorReporter/Editor/ComponentValidation.cs, Localization/en.po, Localization/ja.po, Runtime/MergeBone.cs
=> Merge bone validation

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/MergeSkinnedMeshEditor.cs, Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs, Internal/ErrorReporter/Editor/ComponentValidation.cs, Localization/en.po, Localization/ja.po
=> Validation error for self recursive MergeSkinnedMesh

CHANGELOG-PRERELEASE.md, Editor/ObjectMapping/ObjectMappingBuilder.cs, Editor/OptimizerProcessor.cs, Editor/Processors/MergeBoneProcessor.cs, Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs, Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs, Editor/Processors/TraceAndOptimize/TraceAndOptimizeProcessor.cs, Runtime/TraceAndOptimize.cs
=> Auto merge bone

Localization/ja.po
=> chore(ja): Code review that was late for #430 merge

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/SkinnedMeshes/MeshInfo2.cs
=> fix: broken if there are BlendShapes without moving vertices

CHANGELOG-PRERELEASE.md, Editor/Processors/MergeBoneProcessor.cs
=> fix: MergeBone will break normal and tangent

CHANGELOG-PRERELEASE.md, Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
=> fix: PB for Animator Parameter disappears

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/MergeBoneProcessor.cs, Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs
=> Fix auto merge bone ignores active animation

CHANGELOG-PRERELEASE.md, Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs
=> fix: Transform animation broken

CHANGELOG-PRERELEASE.md, Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
=> fix: StaticRenderer is not removed

.docs/content/docs/tutorial/basic-usage/index.ja.md
=> chore: fix some expression

CHANGELOG-PRERELEASE.md, Editor/Processors/TraceAndOptimize/AnimatorParser.cs
This mark eyelid bones as transforming bones
Fixes #486
=> fix(animator-parser): eyelids with bone is not considered

CONTRIBUTING.md
by https://github.com/anatawa12/AvatarOptimizer/pull/479#discussion_r1329993907
=> chore: nor to or

CHANGELOG-PRERELEASE.md, Editor/Processors/TraceAndOptimize/AnimatorParser.cs
=> fix: left eye disappears

.docs/content/docs/tutorial/basic-usage/index.ja.md, .docs/content/docs/tutorial/basic-usage/index.md
=> fix(docs): image link miss

CHANGELOG-PRERELEASE.md, Editor/Math/Matrix4x4.cs, Editor/Processors/MergeBoneProcessor.cs
=> fix: MergeBone may lost position information with extreamly small object

CHANGELOG-PRERELEASE.md, Editor/Math/Matrix3x3.cs, Editor/Math/Matrix3x3.cs.meta, Editor/Math/Matrix4x4.cs, Editor/Processors/MergeBoneProcessor.cs
=> fix: rotation and lossy scale

CHANGELOG-PRERELEASE.md, CHANGELOG.md
=> docs(changelog): Full EditMode Preview of RemoveMesh Components in rc.5

CHANGELOG-PRERELEASE.md, Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs, Editor/com.anatawa12.avatar-optimizer.editor.asmdef
=> fix: Some missing EntryPoint Components

CHANGELOG-PRERELEASE.md, Editor/LegacyModularAvatarWarning.cs, Editor/LegacyModularAvatarWarning.cs.meta, Editor/com.anatawa12.avatar-optimizer.editor.asmdef, Localization/en.po, Localization/ja.po
=> feat: add warning for Modular Avatar 1.7.0 or older

Test~/BuildAssetBundle.cs, Test~/BuildAssetBundle.cs.meta, Test~/Empty.prefab, Test~/Empty.prefab.meta
Fixes #514
bdunderscore/modular-avatar#452
=> test: add test for runtime build

Editor/OptimizerSession.cs, Editor/Processors/ApplyObjectMapping.cs, Editor/Processors/MeshInfo2Holder.cs, Editor/Processors/OptimizerPlugin.cs, Editor/Processors/SkinnedMeshes/MergeToonLitMaterialProcessor.cs, Editor/Processors/SkinnedMeshes/MeshInfo2.cs, Editor/Processors/TraceAndOptimize/AnimatorParserDebugWindow.cs, Editor/Utils.cs, Test~/MergePhysBoneTest.cs
=> chore: remove asset management system in the AAO

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/DebugConfigWindow.cs, Editor/DebugConfigWindow.cs.meta, Editor/Processors/MergeBoneProcessor.cs
=> hotfix: disable MergeBone BindPose optimization by default

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/MergePhysBoneProcessor.cs
=> fix: MergePhysBone component may remain with no sources

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs
This picks internal GC Debug feature
=> pick gc debug

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/EditModePreview/RemoveMeshPreviewController.cs, Editor/EditModePreview/RemoveMeshWithBoxPreviewContext.cs, Editor/Math/Matrix4x4.cs
=> fix: EditMode Preview of RemoveMeshInBox is not correct

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
=> fix: Default colliders removed

.docs/build.sh, .github/workflows/release.yml, CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/CheckForUpdate.cs, Editor/CheckForUpdate.cs.meta, Editor/Processors/OptimizerPlugin.cs, Localization/en.po, Localization/ja.po
=> Check for update

.docs/content/docs/component-kind/_index.ja.md, .docs/content/docs/reference/_index.ja.md, .docs/content/docs/tutorial/_index.ja.md
=> docs(ja): localize page category

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/ApplyObjectMapping.cs
=> fix(object-mapping): synced layer not proceed correctly

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/ApplyObjectMapping.cs
=> Synced layer again & OverrideController

.github/workflows/gameci-activation.yml, .github/workflows/gameci.yml, .github/workflows/prevent-merging-feature.yml, .github/workflows/release.yml
=> ci: update gameci and other action

.docs/content/docs/tutorial/basic-usage/index.ja.md, .docs/content/docs/tutorial/basic-usage/index.md
自分が実際にドキュメントを読んで困った箇所について加筆しました。
~~github.dev上から編集した為、！？が半角に置換されていますがあしからず。~~ [4d90dad](https://github.com/anatawa12/AvatarOptimizer/pull/574/commits/4d90dad7f045ba13f74a77f09d19d8185a2c5b5b) で直していただきました
=> 「メッシュ」に関する説明を詳しく加筆

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/SkinnedMeshes/MeshInfo2.cs
=> fix: Error if MeshRenderer without MeshFilter

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/ApplyObjectMapping.cs
=> fix: AvatarMask about Humanoid Bone is not working

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
=> fix: Unused Humanoid Bones disappears

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
=> Skip normal check for empty mesh

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs
=> fix: Constraints and Animations may be broken with MergeBone

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/EditModePreview/MeshPreviewController.cs
=> fix: NRE with SMR with None with preview system

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/CheckForUpdate.cs
=> fix: check for update may report latest version incorrectly

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/EditModePreview/MeshPreviewController.cs
=> fix: Preview button is not disabled even if mesh is none

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Internal/ErrorReporter/Editor/ErrorReportUI.cs
=> chore: refresh error report when playmode exit

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Math/Matrix3x3.cs, Editor/Processors/MergeBoneProcessor.cs
=> fix: bindpose optimization may break mesh with bones with scale zero

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/SkinnedMeshes/MeshInfo2.cs
=> chore: remove mesh not readable error

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
=> feat: add support for VRCQuestTools

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/TraceAndOptimize/AutoFreezeBlendShape.cs
=> fix: AutoFreezeBlendshape will freeze with editor value instead of animated constant

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
=> fix: warning with VRCTestMarker

Editor/AutomaticConfiguration.cs, Editor/ObjectMapping/AnimationObjectMapper.cs, Editor/ObjectMapping/ObjectMapping.cs, Editor/ObjectMapping/ObjectMappingBuilder.cs, Editor/ObjectMapping/ObjectMappingContext.cs, Editor/Processors/TraceAndOptimize/AnimatorParser.cs, Editor/Processors/TraceAndOptimize/AnimatorParserDebugWindow.cs, Editor/Processors/TraceAndOptimize/ModificationsContainers.cs, Editor/Processors/TraceAndOptimize/TraceAndOptimizeProcessor.cs, Editor/Utils/ComponentOrGameObject.cs, Editor/Utils/ComponentOrGameObject.cs.meta, Runtime/TraceAndOptimize.cs, Test~/AnimatorParser/AnimatorTest.cs, Test~/ObjectMappingTest.cs
- ObjectMapping system now have copying property
- ObjectMapping system now can move properties of GameObject
=> refactor: ObjectMapping System

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Internal/PrefabSafeSet/Editor/BasicTypeEditors.cs, Internal/PrefabSafeSet/Editor/BasicTypeEditors.cs.meta, Internal/PrefabSafeSet/Editor/PrefabSafeSetEditor.cs
=> fix: prefab blinks when we see editor of PrefabSafeSet of prefab asset

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/ApplyObjectMapping.cs
=> fix: animation clip length can be changed

Editor/com.anatawa12.avatar-optimizer.editor.asmdef, Internal/ErrorReporter/Editor/com.anatawa12.avatar-optimizer.internal.error-reporter.editor.asmdef, Internal/ErrorReporter/Runtime/com.anatawa12.avatar-optimizer.internal.error-reporter.runtime.asmdef, Internal/PrefabSafeSet/Editor/com.anatawa12.avatar-optimizer.internal.prefab-safe-set.editor.asmdef, Internal/PrefabSafeSet/Runtime/com.anatawa12.avatar-optimizer.internal.prefab-safe-set.asmdef, Runtime/com.anatawa12.avatar-optimizer.runtime.asmdef, Test~/Runtime/com.anatawa12.avatar-optimizer.test.runtime.asmdef, Test~/com.anatawa12.avatar-optimizer.test.asmdef
=> chore: use asmdef name instead of guid for reference

API-Editor/ComponentInformation.cs, CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/APIInternal/ComponentInfos.Externals.cs, Editor/APIInternal/ComponentInfos.VRCSDK.cs, Editor/APIInternal/ComponentInfos.cs, Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs, Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs, Editor/Processors/TraceAndOptimize/GCComponentInfo.cs
=> Heavy behaviour

CHANGELOG-PRERELEASE.md, Editor/ObjectMapping/AnimationObjectMapper.cs, Editor/ObjectMapping/ObjectMappingContext.cs, Editor/Utils/Utils.VRCSDK.cs
https://x.com/Roji_Tugaiya/status/1719942755735179496?s=20
=> fix: proxy animation can be remapped

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
=> fix: Joint can be disappeared unexpectedly

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs, Editor/Processors/SkinnedMeshes/MeshInfo2.cs
=> chore: do not add bone for boneless mesh renderer

CHANGELOG-PRERELEASE.md, Editor/ObjectMapping/AnimationObjectMapper.cs, Editor/ObjectMapping/ObjectMappingContext.cs, Test~/ObjectMappingTest.cs
=> Move only not path changed

.docs/Anon.unity, .docs/README.md
=> chore: upgrade anon to 1.06 completely

CHANGELOG-PRERELEASE.md, Editor/ObjectMapping/ObjectMappingContext.cs
=> fix: pptr animation not working

CHANGELOG-PRERELEASE.md, Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
=> fix: enablement mismatched renderers are merged instead of matched renderers

Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
=> fix: enablement detection doesn't use activeness of parents

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/APIInternal/ComponentInfos.cs
=> feat: remove meaningless Renderers and Animators

CHANGELOG-PRERELEASE.md, Editor/APIInternal/ComponentInfos.cs
=> fix: Humanoid of Avatar Root Animator broken

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/OptimizerPlugin.cs, Editor/Processors/OriginalState.cs, Editor/Processors/OriginalState.cs.meta, Editor/Processors/SkinnedMeshes/MeshInfo2.cs, Editor/Processors/SkinnedMeshes/RemoveMeshInBoxProcessor.cs
=> Compatibility with transform moving plugins

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/MergeBoneProcessor.cs, Localization/en.po, Localization/ja.po
=> feat: add error for MergeBone at the Avatar Root

Editor/AnimatorParsers/AnimationParser.cs, Editor/AnimatorParsers/AnimatorParser.cs, Editor/AnimatorParsers/ModificationSource.cs, Editor/AnimatorParsers/ModificationSource.cs.meta, Editor/AnimatorParsers/ModificationsContainers.cs, Editor/Processors/SkinnedMeshes/FreezeBlendShapeProcessor.cs, Internal/ErrorReporter/Editor/ErrorLog.cs, Test~/AnimatorParser/AnimationTest.cs, Test~/com.anatawa12.avatar-optimizer.test.asmdef
=> Animator parser more source

CHANGELOG-PRERELEASE.md, Editor/AnimatorParsers/ModificationsContainers.cs, Editor/Processors/SkinnedMeshes/FreezeBlendShapeProcessor.cs
=> fix(freeze-blendshape): warning for constant animation

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/AutomaticConfiguration.cs, Editor/OptimizerPlugin.cs, Editor/Processors/TraceAndOptimize/OptimizePhysBone.cs, Editor/Processors/TraceAndOptimize/TraceAndOptimizeProcessor.cs, Localization/en.po, Localization/ja.po, Runtime/TraceAndOptimize.cs
=> PhysBone optimization

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/APIInternal/ComponentInfos.DynamicBone.cs, Editor/APIInternal/ComponentInfos.DynamicBone.cs.meta, Editor/APIInternal/ComponentInfos.Externals.cs, Editor/APIInternal/ComponentInfos.FinalIK.cs, Editor/APIInternal/ComponentInfos.FinalIK.cs.meta
=> minimum Finalik support

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/APIInternal/ComponentInfos.FinalIK.cs, Editor/APIInternal/ComponentInfos.VRCSDK.cs, Editor/APIInternal/ComponentInfos.cs, Editor/com.anatawa12.avatar-optimizer.editor.asmdef, Test~/ComponentWhitelistTest.cs, Test~/ComponentWhitelistTest.cs.meta, Test~/com.anatawa12.avatar-optimizer.test.asmdef
=> Imposters and test components

API-Editor/ComponentInformation.cs, CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/APIInternal/ComponentInfos.cs, Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
=> Fixes for particle system

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/MergeBoneProcessor.cs, Test~/MergeBoneTest.cs
=> Merge bone breaks ignore transform

CHANGELOG-PRERELEASE.md, Editor/Processors/MergeBoneProcessor.cs, Test~/MergeBoneTest.cs
=> NRE in merge bone

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/ObjectMapping/AnimationObjectMapper.cs, Editor/ObjectMapping/ObjectMapping.cs, Editor/ObjectMapping/ObjectMappingBuilder.cs, Editor/Utils/Utils.cs, Test~/ObjectMappingTest.cs
=> Fix path resolution duplicated game objects

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/TraceAndOptimize/OptimizePhysBone.cs
=> fix: error with PhysBone Colliders with root bone targets out of avatar (including prefab asset)

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/APIInternal/ComponentInfos.cs
=> fix: null reference exception thrown when extra animators are present

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/AnimatorParsers/AnimatorParser.cs
=> fix: error with generic avatar

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/RemoveMeshInBoxEditor.cs
=> Fix remove mesh in box inspector

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/.MergePhysBoneEditorModificationUtils.ts, Editor/MergePhysBoneEditor.cs, Editor/MergePhysBoneEditorModificationUtils.cs, Editor/MergePhysBoneEditorModificationUtils.generated.cs, Editor/Processors/MergePhysBoneProcessor.cs, Editor/Utils/Utils.VRCSDK.cs, Localization/en.po, Localization/ja.po, Test~/MergePhysBoneTest.cs
=> fix: merge PhysBone curve

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/APIInternal/ComponentInfos.cs
=> fix: error with generic avatar in 2022

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Internal/PrefabSafeSet/Runtime/PrefabSafeSet.cs
=> Assign instead of assert

CHANGELOG-PRERELEASE.md, Editor/ObjectMapping/ObjectMappingContext.cs
No changelog because small catch.
=> Fix: Object mapping did not work

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
=> fix: unknown component warning were shown multiple time for one type

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/APIInternal/ComponentInfos.VRCSDK.cs
=> fix: empty armature trick broken

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/MeshInfo2Holder.cs
=> chore: avoid `Array index (n) is out of bounds (size=m)` error

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/APIInternal/ComponentInfos.cs
=> fix: humanoid bones itself are not included

README.md
=> docs(readme): update api stability note

.docs/content/_index.ja.md, .docs/content/_index.md, .docs/layouts/shortcodes/beta-only.html
Fixes #836
Fixes #827 with documentation
=> docs(index): add note about NDMF prereleases

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/TraceAndOptimize/GCDebug.cs
=> fix: inspector of ComponentTypePair (GCDebug) is broken

CHANGELOG-PRERELEASE.md, CHANGELOG.md, package.json
=> chore: add license, documentationUrl, and changelogUrl to package.json

CHANGELOG-PRERELEASE.md, CHANGELOG.md, CONTRIBUTING.md, Editor/AnimatorParserV2/PropModNode.cs, Editor/DestroyTracker.cs, Editor/DestroyTracker.cs.meta, Editor/ObjectMapping/ObjectMappingBuilder.cs, Editor/OptimizerPlugin.cs, Editor/Processors/EditSkinnedMeshComponentProcessor.cs, Editor/Processors/MakeChildrenProcessor.cs, Editor/Processors/MergeBoneProcessor.cs, Editor/Processors/MergePhysBoneProcessor.cs, Editor/Processors/RemoveZeroSizedPolygonProcessor.cs, Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs, Editor/Processors/SkinnedMeshes/MergeToonLitMaterialProcessor.cs, Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs, Editor/Processors/TraceAndOptimize/OptimizePhysBone.cs, Editor/Processors/TraceAndOptimize/TraceAndOptimizeProcessor.cs
=> Remove modification from destroyed objects

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/APIInternal/ComponentInfos.cs
=> fix: nested constraint may be broken

CHANGELOG-PRERELEASE.md, package.json
=> chore(deps): revert NDMF to 1.3.0-rc.3

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/APIInternal/ComponentInfos.VRCSDK.cs
=> chore: remove PhysBones which swung nothing

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/AnimatorOptimizer/AOUtils.cs, Editor/Processors/AnimatorOptimizer/AnimOptPassBase.cs, Editor/Processors/AnimatorOptimizer/EntryExitToBlendTree.cs, Test~/AnimatorOptimizer/EntryExitToBlendTree/Animation7.curve.anim, Test~/AnimatorOptimizer/EntryExitToBlendTree/Animation7.curve.anim.meta, Test~/AnimatorOptimizer/EntryExitToBlendTree/EntryExitToBlendTreeTest.cs, Test~/AnimatorOptimizer/EntryExitToBlendTree/GestureNonConvertibleBecauseCurve.controller, Test~/AnimatorOptimizer/EntryExitToBlendTree/GestureNonConvertibleBecauseCurve.controller.meta
=> Fix time dependent animation

Editor/AnimatorParserV2/AnimationParser.cs, Editor/AnimatorParserV2/AnimatorParser.cs, Editor/AnimatorParserV2/AnimatorParserDebugWindow.cs, Editor/AnimatorParserV2/NodeContainer.cs, Editor/AnimatorParserV2/PropModNode.cs, Editor/AnimatorParserV2/Utilities.cs, Editor/ContextExtensions.cs, Editor/ObjectMapping/ObjectMappingBuilder.cs, Test~/AnimatorParser/AnimatorTest.cs, Test~/AnimatorParser/TestUtil.cs
=> Object reference curve in animator parser

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/SkinnedMeshes/FreezeBlendShapeProcessor.cs
=> chore: don't wan animated blend shape warning if animated to few constant

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/ComponentValidation.cs, Editor/Processors/MergeBoneProcessor.cs, Test~/ComponentWhitelistTest.cs, Test~/EnumValues.cs, Test~/MergeBoneTest.cs
Fixed some compile errors I've found when using AvatarOptimizer in non-VRChat project.
(Reincarnation of PR #883)
=> chore: Add conditional compile for VRCSDK API (for master)

Localization/ja.po
=> chore: remove redundant whitespace from translation

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/SkinnedMeshes/MeshInfo2.cs
=> fix: mesh renderers with none mesh will become mesh with no polygons

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/ComponentValidation.cs, Editor/Processors/MergeBoneProcessor.cs, Test~/ComponentWhitelistTest.cs, Test~/EnumValues.cs, Test~/MergeBoneTest.cs
chore: Add conditional compile for VRCSDK API (for master)
Backport of #884
=> Backport #884

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
=> fix: if some component refers external component, internal error

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/APIInternal/ComponentInfos.VRCSDK.cs, Editor/ObjectMapping/ObjectMappingContext.cs, Editor/com.anatawa12.avatar-optimizer.editor.asmdef, Test~/ComponentWhitelistTest.cs
=> VRCSDK 3.5.2 beta.1 support

.github/workflows/gameci.yml
=> pick 2022 ci

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/EditModePreview/MeshPreviewController.cs
=> fix: null reference exception with MeshPreviewController

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/APIInternal/ComponentInfoRegistry.cs
=> fix: ContextHolder become unknown component in NDMF 1.4.0

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Runtime/MergePhysBone.cs
=> chore(merge-physbone): make endpointPosition copy by default instead of clear

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/AnimatorParserV2/PropModNode.cs, Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs, Editor/Utils/AnimationLocation.cs
=> Merge Skinned Mesh activeness animation warning improvements

API-Editor/ComponentInformation.cs, CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/APIInternal/ComponentInfos.cs, Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
=> Path dependency in component information

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/EditModePreview/MeshPreviewController.cs
=> Fix Editmode preview

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/ConfigureClampBlendShape.cs, Editor/ConfigureClampBlendShape.cs.meta
=> feat: configuring legacy clamp blendShape weights

API-Editor/ComponentInformation.cs, CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/APIInternal/ComponentInfos.VRCSDK.cs, Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs, Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs
=> Remove PhysBone or Contact Receiver if it's not used by Animator Controller

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Internal/PrefabSafeSet/Editor/BasicTypeEditors.cs
=> feat(prefab-safe-set): add all components on the GameObject with Drag and Drop

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/AnimatorParserV2/AnimatorParser.cs
=> fix: PlayableLayerControl or AnimatorLayerControl on non-root animator are ignored

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/AnimatorParserV2/PropModNode.cs, Test~/AnimatorParser/Issue967.meta, Test~/AnimatorParser/Issue967/FX.controller, Test~/AnimatorParser/Issue967/FX.controller.meta, Test~/AnimatorParser/Issue967/FX_0_0.anim, Test~/AnimatorParser/Issue967/FX_0_0.anim.meta, Test~/AnimatorParser/Issue967/FX_1_0.anim, Test~/AnimatorParser/Issue967/FX_1_0.anim.meta, Test~/AnimatorParser/Issue967/FX_1_1.anim, Test~/AnimatorParser/Issue967/FX_1_1.anim.meta, Test~/AnimatorParser/Issue967/TestIssue967.cs, Test~/AnimatorParser/Issue967/TestIssue967.cs.meta
=> Falsey detcted as constant

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Internal/AnimatorOptimizer/EntryExitToBlendTree.cs, Internal/Utils/ACUtils.cs, Test~/AnimatorOptimizer/AnimatorOptimizerTestBase.cs, Test~/AnimatorOptimizer/EntryExitToBlendTree/Issue969.meta, Test~/AnimatorOptimizer/EntryExitToBlendTree/Issue969/0.anim, Test~/AnimatorOptimizer/EntryExitToBlendTree/Issue969/0.anim.meta, Test~/AnimatorOptimizer/EntryExitToBlendTree/Issue969/1.anim, Test~/AnimatorOptimizer/EntryExitToBlendTree/Issue969/1.anim.meta, Test~/AnimatorOptimizer/EntryExitToBlendTree/Issue969/FX_0.controller, Test~/AnimatorOptimizer/EntryExitToBlendTree/Issue969/FX_0.controller.meta, Test~/AnimatorOptimizer/EntryExitToBlendTree/Issue969/FX_1.controller, Test~/AnimatorOptimizer/EntryExitToBlendTree/Issue969/FX_1.controller.meta, Test~/AnimatorOptimizer/EntryExitToBlendTree/Issue969/FX_2.controller, Test~/AnimatorOptimizer/EntryExitToBlendTree/Issue969/FX_2.controller.meta, Test~/AnimatorOptimizer/EntryExitToBlendTree/Issue969/FX_3.controller, Test~/AnimatorOptimizer/EntryExitToBlendTree/Issue969/FX_3.controller.meta, Test~/AnimatorOptimizer/EntryExitToBlendTree/Issue969/FX_4.controller, Test~/AnimatorOptimizer/EntryExitToBlendTree/Issue969/FX_4.controller.meta, Test~/AnimatorOptimizer/EntryExitToBlendTree/Issue969/Issue969Test.cs, Test~/AnimatorOptimizer/EntryExitToBlendTree/Issue969/Issue969Test.cs.meta
=> Improve entry exit to BlendTree optimization

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Internal/AnimatorOptimizer/MergeDirectBlendTree.cs
=> fix(merge-direct-blend-tree): fix skip option

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/SkinnedMeshes/MeshInfo2.cs
=> fix: bounds broken with updateWhenOffscreen = true

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/ObjectMapping/AnimationObjectMapper.cs, Test~/Basic/ObjectMappingTest.cs
https://misskey.niri.la/notes/9ru5nrhw63
=> feat: remove animations about missing GameObject

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs, Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs, Editor/Processors/TraceAndOptimize/RequireComponentCache.cs, Editor/Processors/TraceAndOptimize/RequireComponentCache.cs.meta
=> fix: remove component can be fails with RequireComponent attribute

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/TraceAndOptimize/AutoMergeSkinnedMesh.cs
=> fix: NRE with AutoMergeSkinnedMesh

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Internal/MeshInfo2/MeshInfo2.cs, Localization/en-us.po, Localization/ja-jp.po
=> R/W Mesh off make error again

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Inspector/RemoveMeshInBoxEditor.cs
=> fix: inspector of remove mesh in box is broken

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/TraceAndOptimize/AutoMergeSkinnedMesh.cs
=> fix(auto-merge-smr): do not merge if used by other components

.github/workflows/release.yml
=> ci: update changelog url on release action

.github/workflows/release.yml
=> ci: unchanged package.json is uploaded to release

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/TraceAndOptimize/AutoFreezeBlendShape.cs
=> chore: skip AutoFreezeBlendShape for Cloth SkinnedMeshRenderers

.docs/content/docs/developers/asset-description/index.en.md, .docs/content/docs/developers/asset-description/index.ja.md, .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md, .docs/content/docs/developers/make-your-components-compatible-with-aao/index.md
=> docs(make-your-components-compatible-with-aao): add Asset Description in How to improve the compatibility

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/RemoveInvalidProperties.cs
=> fix(remove-invalid-properties): broken material slot animation for multi pass rendering

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
=> fix: particle system with bone-skinned skinned mesh renderer will break

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Internal/AnimatorOptimizer/EntryExitToBlendTree.cs
=> fix: none motion in default state

CHANGELOG-PRERELEASE.md, CHANGELOG.md, package.json
=> chore: declare SDK 3.6.0 compatibility

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/RemoveInvalidProperties.cs
=> fix: some rare material swap animation will be broken

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Internal/AnimatorOptimizer/MergeBlendTreeLayer.cs, Test~/AnimatorOptimizer/MergeBlendTreeLayer/Animation 0.anim, Test~/AnimatorOptimizer/MergeBlendTreeLayer/Animation 2.anim, Test~/AnimatorOptimizer/MergeBlendTreeLayer/Animation 3.anim, Test~/AnimatorOptimizer/MergeBlendTreeLayer/Animation 3.anim.meta, Test~/AnimatorOptimizer/MergeBlendTreeLayer/Animation 4.anim, Test~/AnimatorOptimizer/MergeBlendTreeLayer/Animation 4.anim.meta, Test~/AnimatorOptimizer/MergeBlendTreeLayer/Animation 5.anim, Test~/AnimatorOptimizer/MergeBlendTreeLayer/Animation 5.anim.meta, Test~/AnimatorOptimizer/MergeBlendTreeLayer/BlockedCompletely.controller, Test~/AnimatorOptimizer/MergeBlendTreeLayer/BlockedCompletely.controller.meta, Test~/AnimatorOptimizer/MergeBlendTreeLayer/BlockedCompletely.converted.controller, Test~/AnimatorOptimizer/MergeBlendTreeLayer/BlockedCompletely.converted.controller.meta, Test~/AnimatorOptimizer/MergeBlendTreeLayer/BlockedPartially.controller, Test~/AnimatorOptimizer/MergeBlendTreeLayer/BlockedPartially.controller.meta, Test~/AnimatorOptimizer/MergeBlendTreeLayer/BlockedPartially.converted.controller, Test~/AnimatorOptimizer/MergeBlendTreeLayer/BlockedPartially.converted.controller.meta, Test~/AnimatorOptimizer/MergeBlendTreeLayer/ConvertibleSimple.controller, Test~/AnimatorOptimizer/MergeBlendTreeLayer/ConvertibleSimple.converted.controller, Test~/AnimatorOptimizer/MergeBlendTreeLayer/ConvertibleSimple.meaningless-removed.controller, Test~/AnimatorOptimizer/MergeBlendTreeLayer/MergeBlendTreeLayerTest.cs
=> fix: merge blendtree layers with overrides

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/TraceAndOptimize/AutoMergeSkinnedMesh.cs, Editor/Processors/TraceAndOptimize/OptimizePhysBone.cs, Internal/Utils/RoundError.cs, Internal/Utils/RoundError.cs.meta
=> Allow precision error for merge physbone

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
=> chore: do not generate animation warning if source is not animated

API-Editor/ComponentInformation.cs, CHANGELOG-PRERELEASE.md, CHANGELOG.md, Runtime/API/PrefabSafeSetAccessor.cs, Runtime/APIChecker.cs, Runtime/APIChecker.cs.meta, Runtime/MergeSkinnedMesh.cs, Runtime/RemoveMeshByBlendShape.cs, Runtime/RemoveMeshInBox.cs, Runtime/TraceAndOptimize.cs, Test~/Basic/PublicApiCheck.cs
=> Warning for bad api usage

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/APIInternal/ComponentInfos.cs
=> fix: Particles with MeshRenderer shape will be broken

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/ObjectMapping/ObjectMappingContext.cs, Editor/com.anatawa12.avatar-optimizer.editor.asmdef
=> fix: VRCAnimatorPlayAudio support is broken

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/EditModePreview/RemoveMeshPreviewController.cs, Editor/Processors/SkinnedMeshes/RemoveMeshByMaskProcessor.cs
=> fix: IndexOutOfRange with remove mesh in box

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/AnimatorParserV2/NodeContainer.cs
=> fix: NRE with Generic Avatar

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Internal/MeshInfo2/MeshInfo2.cs
=> fix: mesh is broken if all weighted bones are none

.github/workflows/gameci.yml, CHANGELOG-PRERELEASE.md, CHANGELOG.md, package.json
=> Start v 1.8 series

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/APIInternal/ComponentInfos.VRCSDK.cs
=> fix: VRCConstraints with Target will be removed unexepctedly

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Inspector/MergePhysBoneEditor.cs, Editor/Processors/MergePhysBoneProcessor.cs
=> fix: validation process for MergePhysBone with specified target parent is broken

Localization/en-us.po, Localization/ja-jp.po
=> feat: add many hints to warnings

.docs/content/docs/reference/trace-and-optimize/index.ja.md, .docs/content/docs/reference/trace-and-optimize/index.md
=> docs: Convert AnyState to Entry-Exit

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Internal/MeshInfo2/MeshInfo2.cs
=> feat: optimize index buffer with baseVertex

.docs/content/docs/reference/merge-skinned-mesh/index.ja.md, .docs/content/docs/reference/merge-skinned-mesh/index.md, CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Inspector/MergeSkinnedMeshEditor.cs, Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs, Editor/Utils/AnimationLocation.cs, Internal/Localization/Editor/BuildLog.cs, Internal/Utils/Utils.cs, Localization/en-us.po, Localization/ja-jp.po, Runtime/MergeSkinnedMesh.cs, Test~/Basic/MergeSkinnedMeshTest.cs, Test~/Basic/MergeSkinnedMeshTest.cs.meta, Test~/Basic/com.anatawa12.avatar-optimizer.test.basic.asmdef, Test~/Utils/AnimatorControllerGenerator.cs, Test~/Utils/AnimatorControllerGenerator.cs.meta, Test~/Utils/LogTest.cs, Test~/Utils/LogTest.cs.meta, Test~/Utils/TestUtils.cs
=> Merge Skinned Mesh Enablement Animation

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Internal/MeshInfo2/MeshInfo2.cs, Localization/en-us.po, Localization/ja-jp.po, Localization/zh-cn.po, Localization/zh-hant.po
=> R/W off mesh support (with Av3Emulator)

CHANGELOG-PRERELEASE.md, CHANGELOG.md, ExternalDescriptions/AvatarModifySupport.asset, ExternalDescriptions/AvatarModifySupport.asset.meta
2024/09/21現在しなのちゃん https://booth.pm/ja/items/6106863 にてアーリーアクセスとして配布されているAvater Modify Support (AMS)に関するAsset Descriptionです。
Asset DescriptionのComment欄にもそのことがわかるように記載しています。
=> feat: AvatarModifySupport Asset Description

.docs/assets/_custom.scss
ドキュメントのスタイルを整えました。scssの変更のみ行っています。
=> docs(scss): Create a style

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/ObjectMapping/ObjectMappingContext.cs
=> fix: NRE with newly created VRCAnimatorPlayAudio

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/APIInternal/ComponentInfos.cs
=> fix: Particle System uses local scale will be broken

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/APIInternal/ComponentInfos.VRCSDK.cs
=> fix: Avatars with Visame Skinned Mesh disabled will not able to upload

API-Editor/ShaderInformation.cs, Editor/APIInternal/ShaderInformation.Liltoon.cs, Editor/Processors/TraceAndOptimize/OptimizeTexture.cs
=> Improve Shader Knowlage

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/AnimatorParserV2/AnimationParser.cs, Editor/AnimatorParserV2/AnimatorControllerPropModNode.cs, Editor/AnimatorParserV2/PropModNode.cs, Editor/ObjectMapping/ObjectMappingContext.cs
=> Additive reference pose support and improvements on additive support

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/AssetDescription.cs
=> fix(editor): fix typo in [CreateAssetMenu] label

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/TraceAndOptimize/OptimizeTexture.cs
=> fix: Optimize Texture broken with crunch compression

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Runtime/RemoveMeshInBox.cs
=> fix: default value for RemoveMeshInBox differs between editmode and playmode

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/AnimatorParserV2/AnimatorParser.cs, Editor/AnimatorParserV2/PropModNode.cs, Editor/Processors/TraceAndOptimize/OptimizeTexture.cs, Internal/Utils/UnionFind.cs, Internal/Utils/UnionFind.cs.meta
=> Optimize Texture improvements

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/AnimatorParserV2/AnimatorParserDebugWindow.cs
=> feat: support pptr / object reference animation in animator parser debug window

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Internal/PrefabSafeSet/Editor/PrefabSafeSetRuntimeEditorImpl.cs
=> fix: IndexOutOfBounds in OnValidate of PrefabSafeSet

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/MergePhysBoneEditorModificationUtils.cs
=> fix: maxSquish cannot be configured for mergePB

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/MergeBoneProcessor.cs, Editor/Processors/RemoveZeroSizedPolygonProcessor.cs, Editor/Processors/SkinnedMeshes/FreezeBlendShapeProcessor.cs, Editor/Processors/SkinnedMeshes/InternalAutoFreezeMeaninglessBlendShapeProcessor.cs, Editor/Processors/SkinnedMeshes/RemoveMeshByBlendShapeProcessor.cs, Internal/MeshInfo2/AsssemblyInfo.cs, Internal/MeshInfo2/AsssemblyInfo.cs.meta, Internal/MeshInfo2/MeshInfo2.cs, Test~/MeshInfo2/MeshInfo2Test.cs
=> Performance improvements on Meshinfo2 with changing blendShape save format

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/TraceAndOptimize/OptimizeTexture.cs, Internal/Utils/Utils.cs
=> fix(optimize-texture): error with merge skinned mesh and animation

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/AnimatorParserV2/AnimatorControllerPropModNode.cs, Editor/AnimatorParserV2/AnimatorParser.cs, Editor/AnimatorParserV2/AnimatorParserDebugWindow.cs, Editor/AnimatorParserV2/NodeContainer.cs, Editor/AnimatorParserV2/PropModNode.cs, Editor/AnimatorParserV2/Utilities.cs, Editor/ContextExtensions.cs, Editor/ObjectMapping/PropertyInfo.cs, Editor/Processors/MergePhysBoneProcessor.cs, Editor/Processors/ParseAnimator.cs, Editor/Processors/SkinnedMeshes/FreezeBlendShapeProcessor.cs, Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs, Editor/Processors/TraceAndOptimize/AutoFreezeBlendShape.cs, Editor/Processors/TraceAndOptimize/AutoMergeSkinnedMesh.cs, Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs, Editor/Processors/TraceAndOptimize/OptimizePhysBone.cs, Editor/Processors/TraceAndOptimize/OptimizeTexture.cs, Editor/Utils/AnimationLocation.cs, Test~/AnimatorParser/AnimatorTest.cs, Test~/AnimatorParser/Issue967/TestIssue967.cs, Test~/AnimatorParser/TestUtil.cs, Test~/Basic/AutoMergeSkinnedMeshTest.cs, Test~/Utils/AnimatorControllerGenerator.cs
Initial fix for #1244, but not closing because we should implement removing layers
=> Weight 0 layer affectness

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/TraceAndOptimize/AutoMergeSkinnedMesh.cs, Test~/Basic/AutoMergeSkinnedMeshTest.cs, Test~/Utils/AnimatorControllerGenerator.cs
=> fix: InvalidOperationException in AutoMergeSkinnedMesh

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Internal/MeshInfo2/MeshInfo2.cs, Test~/MeshInfo2/MeshInfo2Test.cs
=> Fix error with empty submesh

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Internal/MeshInfo2/MeshInfo2.cs, Test~/MeshInfo2/MeshInfo2Test.cs
=> Remove Mesh in Box broken with Mesh without Bones

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Inspector/RemoveMeshInBoxEditor.cs
=> chore: hide transform gizmo when editing box of Remove Mesh in Box

Editor/APIInternal/ShaderInformation.Liltoon.cs
=> chore: declare liltoon 1.8.2 compatibility

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Runtime/MergePhysBone.cs
=> chore: implement INetworkID in MergePhysBone

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/SkinnedMeshes/EditSkinnedMeshProcessor.cs
=> fix: NullReferenceException with None mesh in SkinnedMeshRenderer

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/AnimatorParserV2/AnimationParser.cs, Editor/AnimatorParserV2/AnimatorParser.cs, Editor/Processors/ParseAnimator.cs, Editor/Processors/TraceAndOptimize/AutoMergeSkinnedMesh.cs
=> fix: incorrect AutoMergeSkinnedMesh with material property animations (1.7)

API-Editor/ShaderInformation.cs, Editor/APIInternal/ShaderInformation.Liltoon.cs, Editor/OptimizerPlugin.cs, Editor/Processors/ShaderMaterialInformation.cs, Editor/Processors/ShaderMaterialInformation.cs.meta, Editor/Processors/TraceAndOptimize/OptimizeTexture.cs, Test~/Basic/OptimizeTextureTest.cs
Prepares #482 
No changelog for release since refactoring
=> Save material info and call infromation once

API-Editor/ShaderInformation.cs, CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/APIInternal/ShaderInformation.Liltoon.cs, Editor/ContextExtensions.cs, Editor/Processors/ShaderMaterialInformation.cs, Editor/Processors/TraceAndOptimize/AutoMergeSkinnedMesh.cs
=> feat: support shaders uses vertex index

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs, Editor/Processors/TraceAndOptimize/AutoMergeSkinnedMesh.cs
=> fix: Animation for target renderer of Merge Skinned Mesh might be overridden by animation for source renderer

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/ShaderMaterialInformation.cs
=> fix: nre when no aao component attached

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Internal/PrefabSafeSet/Runtime/PrefabSafeUniqueCollection.cs
=> fix: InvalidOperationException in PSUCRuntimeUtil

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/NewGameObjectAndAddComponent.cs, Editor/NewGameObjectAndAddComponent.cs.meta
=> feat: NewGameObjectAndAddComponent

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Inspector/RenameBlendShapeEditor.cs, Editor/Processors/SkinnedMeshes/RenameBlendShapeProcessor.cs, Localization/en-us.po, Localization/ja-jp.po, Test~/Basic/RenameBlendShapeTest.cs
=> chore!: remove merge feature from rename blendShape

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
=> fix: NRE if specified expression parameters is None

API-Editor/ShaderInformation.cs, CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/ShaderMaterialInformation.cs, Editor/Processors/TraceAndOptimize/AutoMergeSkinnedMesh.cs, Internal/Utils/Utils.cs
=> fix: 'shader' doesn't have a float or range property 'prop' error

Localization/en-us.po, Localization/ja-jp.po
https://github.com/anatawa12/AvatarOptimizer/pull/1296#issuecomment-2439272330
=> chore(ja/en): l10n follow 1296

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/OptimizerPlugin.cs
=> fix: AAO not enabled if all components are on inactive GameObjects

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/TraceAndOptimize/AutoMergeBlendShape.cs
=> fix: animation broken with auto merge blendShape

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs, Editor/Processors/TraceAndOptimize/OptimizeTexture.cs
Fix https://x.com/7_palms/status/1853336381998952493
=> fix: basic Mesh Renderers are not considered in Optimize Texture

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/MergePhysBoneProcessor.cs, Localization/en-us.po
=> chore: add warning for animation and limit rotation fix

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/MergePhysBoneProcessor.cs, Localization/en-us.po
=> chore: make error for MergeBone with MergePB rotation mode fix

API-Editor/ShaderInformation.cs, CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/APIInternal/ShaderInformation.Standard.cs, Editor/APIInternal/ShaderInformation.Standard.cs.meta, Editor/APIInternal/ShaderInformation.VRCSDK.cs, Editor/APIInternal/ShaderInformation.VRCSDK.cs.meta, Editor/Processors/ShaderMaterialInformation.cs
=> More shader support for optimize texture

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Internal/PrefabSafeSet/Editor/UniqueCollection/PrefabSafeUniqueCollectionRuntimeEditorImpl.cs
=> fix: NRE on save prefab from PrefabStage

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/InitializeAnimatorOptimizer.cs
=> fix: Errors if exactly same AnimatorController is specified for playable layers

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Internal/PrefabSafeSet/Editor/Set/PrefabSafeSetEditor.cs, Localization/en-us.po
=> feat: add remove button for prefab safe set

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/APIInternal/ShaderInformation.Liltoon.cs, Internal/MeshInfo2/MeshInfo2.cs
=> fix: UV1 channel is changed even if _MatCap(2nd)?BlendUV1 is not zero

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
=> fix: preventing removing viseme blendShapes not working for manual Merge Skinned Mesh

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs, Localization/en-us.po, Localization/ja-jp.po, Test~/Basic/MergeSkinnedMeshTest.cs
=> fix: missing localization for copy enablement animation related errors

.docs/content/docs/tutorial/basic-usage/index.md
Fix https://github.com/anatawa12/AvatarOptimizer/pull/1406#discussion_r1968588333
=> docs: fix dup lines

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs, Internal/MeshInfo2/MeshInfo2.cs, Internal/TraceAndOptimizeBase/TraceAndOptimizeProcessor.cs, Runtime/TraceAndOptimize.cs
=> Fix mesh for particle system borken

.docs/internals/animator-parser-debug-window.ja.md
=> docs: add animator parser debug window doc

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/APIInternal/ComponentInfos.VRCSDK.cs, Editor/APIInternal/ComponentInfos.cs, Editor/APIInternal/UVUsageCompabilityAPIImpl.cs, Editor/AnimatorParserV2/AnimatorParser.cs, Editor/ComponentValidation.cs, Editor/EditModePreview/AAORenderFilterBase.cs, Editor/Inspector/RemoveMeshByMaskEditor.cs, Editor/Inspector/RemoveMeshByUVTileEditor.cs, Editor/Inspector/UnusedBonesByReferencesToolEditor.cs, Editor/Processors/MergeBoneProcessor.cs, Editor/Processors/MergePhysBoneProcessor.cs, Editor/Processors/RemoveZeroSizedPolygonProcessor.cs, Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs, Editor/Processors/TraceAndOptimize/AutoFreezeBlendShape.cs, Editor/Processors/TraceAndOptimize/AutoMergeSkinnedMesh.cs, Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs, Runtime/RemoveMeshByUVTile.cs
To avoid unnecessary allocation.
=> Replace `GetComponent` with `TryGetComponent`

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/TraceAndOptimize/GCComponentInfo.cs
Regression from #1242 / 9571ba34de14fc37aa7b04828c2c6cb90c1d841f
=> fix: Particle System are not removed correctly

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/APIInternal/ComponentInfos.VRCFury.cs, Editor/APIInternal/ComponentInfos.VRCSDK.cs, Editor/APIInternal/ComponentInfos.cs
=> Updates to Component Information

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/MergePhysBoneProcessor.cs
=> fix: parameter is not set for MergePhysBone

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/APIInternal/ShaderInformation.VRCSDK.cs
=> feat: ToonStandard Shader Support for Texture Optimization

package.json
beta releases are allowed from first for new NDMF support
=> chore: start 1.9.0 series

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/ObjectMapping/ObjectMappingContext.cs
=> fix: infinite recursion when additiveReferencePoseClip has recursion

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/SkinnedMeshes/MergeToonLitMaterialProcessor.cs
=> fix: generating preview of MergeToonLit do not work

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/ObjectMapping/AnimationObjectMapper.cs, Editor/ObjectMapping/ObjectMappingContext.cs, Test~/Basic/MergeSkinnedMeshTest.cs, Test~/Basic/ObjectMappingTest.cs
=> fix: automatic toggle may create toggle for different object when multiple components on single object

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/OptimizerPlugin.cs, Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs, Editor/Processors/TraceAndOptimize/RemoveSubMeshesWithoutMaterial.cs, Editor/Processors/TraceAndOptimize/RemoveSubMeshesWithoutMaterial.cs.meta
=> chore: remove submeshes without materials first

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/MergeBoneProcessor.cs, Internal/Utils/ReferenceEqualityComparer.cs, Internal/Utils/ReferenceEqualityComparer.cs.meta, Internal/Utils/Utils.cs
=> fix: EnsureRunningOnMainThread can only be called from the main thread

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/Processors/TraceAndOptimize/OptimizeTexture.cs
=> fix: error in OptimizeTexture with remove unused objects disabled

CHANGELOG-PRERELEASE.md, CHANGELOG.md, Editor/AnimatorParserV2/AnimationParser.cs, Editor/AnimatorParserV2/AnimatorControllerPropModNode.cs, Editor/AnimatorParserV2/AnimatorParser.cs, Editor/AnimatorParserV2/PropModNode.cs, Editor/Processors/InitializeAnimatorOptimizer.cs, Editor/Processors/SkinnedMeshes/InternalAutoFreezeNonAnimatedBlendShapesProcessor.cs, Internal/Utils/AnimatorWeightChange.cs, Test~/AnimatorParser/AnimatorTest.cs, Test~/AnimatorParser/TestUtil.cs, Test~/Basic/AutoFreezeBlendShapeTest.cs, Test~/Basic/AutoFreezeBlendShapeTest.cs.meta
=> Variable weight support

Editor/Processors/ShaderMaterialInformation.cs, Editor/Processors/TraceAndOptimize/AutoMergeSkinnedMesh.cs, Editor/Processors/TraceAndOptimize/OptimizeTexture.cs, Editor/Processors/TraceAndOptimize/RemoveUnusedMaterialProperties.cs, Internal/Utils/EqualsHashSet.cs, Internal/Utils/Mocks.cs
=> Better Shader Information
