anatawa12/AvatarOptimizer

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/Migration/Migration.cs

Fixes #48 の対応
v0.1.4におけるMergeSkinnedMeshにNullが含まれていた場合、Migrationが失敗してしまうことの修正

Migration処理の修正

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/Processors/SkinnedMeshes/RemoveMeshInBoxProcessor.cs

#59 の対応
RemoveMeshInBoxProcessorにて判定に使っているのがv1のRemoveMeshInBox.boxesのままになっていたため、boxlistを見るように修正

RemoveMeshInBoxが正常に動作しないことの修正

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/MergeSkinnedMeshWindow.cs
Editor/Processors/SkinnedMeshes/MeshInfo2.cs

Mesh broken with many vertices

---

CHANGELOG-PRERELEASE.md
Editor/MergePhysBoneEditor.cs

https://feedback.vrchat.com/open-beta/p/sdk-320-beta1-max-squish-is-shown-in-the-physbone-10
> As some others have indicated, Squish does work in version 1.0. The patch notes also say this in some places... and contradict it in others. Whoops. Sorry for the lack of clarity there!

fix: we can use Max Squish in PhysBone 1.0

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/OptimizerProcessor.cs
Editor/Utils.cs

Not working with VRCFury

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/Migration/Migration.cs

Fixes #135
`AssetDatabase#FindAssets` に `Assets/` フォルダのみのフィルタを掛けることで修正

fix: migration should check for read only package

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/ObjectMapping.cs
Editor/ObjectMapping.cs.meta
Editor/OptimizerSession.cs
Editor/Processors/ApplyObjectMapping.cs
Editor/Processors/DeleteGameObjectProcessor.cs
Editor/Processors/MakeChildrenProcessor.cs
Editor/Processors/MergeBoneProcessor.cs
Editor/Processors/MergePhysBoneProcessor.cs
Editor/Processors/SkinnedMeshes/EditSkinnedMeshProcessor.cs
Editor/Processors/SkinnedMeshes/FreezeBlendShapeProcessor.cs
Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
Editor/Processors/SkinnedMeshes/MeshInfo2.cs
Editor/Utils.cs
Test~/ObjectMappingTest.cs
Test~/ObjectMappingTest.cs.meta
Test~/UtilsTest.cs
Test~/UtilsTest.cs.meta

Remake object mapping system

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Internal/ErrorReporter/Editor/BuildReport.cs
Internal/ErrorReporter/Editor/ErrorReportUI.cs
Internal/ErrorReporter/Editor/Resources/com.anatawa12.avatar-optimizer.error-report.uss

Error reporting window improvements

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/MergePhysBoneEditor.cs

Fix #220 
`MergePhysBoneEditorModificationUtils.DoProcess()` 内でserializedObjectからプロパティを取得する前にプロパティの保存をしていないようです。
そのため、マージしたいPhysBoneをD&Dしてきても何も起きてないように見える現象が起きます。
描画前にApplyしてしまえば問題なさそうでしたので、draw custom editorの直前でApplyすることで修正しました。
もし他の手段で修正中などであればCloseしていただいて問題ないです。

Apply modified properties before draw custom editor

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Internal/ErrorReporter/Editor/ErrorReportUI.cs

fix: NRE if the window exists in background

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/Processors/ApplyObjectMapping.cs
Internal/ErrorReporter/Editor/BuildReport.cs
Localization/en.po
Localization/ja.po

Fix eyelids bugs

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
Editor/Processors/SkinnedMeshes/MeshInfo2.cs

I noticed when using any of the mesh modifying tools with Mamehinata, the outlines would disappear. I tracked it down to a problem with meshes that are imported with "Tangents: None". `MeshInfo2` assumed that all meshes have tangents and would assign tangents to the new mesh.
メッシュを変更する道具はまめひなたちゃんに使うと輪郭を消するのを気づきました。FBXを入る時に「Tangents: None」を使うの問題が見つけました。`MeshInfo2`はtangentなしメッシュがありませんと思い込みて新しいメッシュにtangentを入りました。
The Unity documentation says that normals are also optional. Unityの文献集はnormalがないメッシュもあると言います。
Mamehinata's FBX import settings:
Demo scene that demonstrates the issue without Mamehinata (requires liltoon and AvatarOptimizer):
[demo.zip](https://github.com/anatawa12/AvatarOptimizer/files/12139605/demo.zip)

fix tangentless mesh

---

.docs/content/docs/reference/automatic-configuration/index.ja.md
.docs/content/docs/reference/automatic-configuration/index.md
CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/AutomaticConfiguration.cs
Editor/Processors/AutomaticConfiguration/AutomaticConfigurationProcessor.CollectUsages.cs
Editor/Processors/AutomaticConfiguration/AutomaticConfigurationProcessor.FindUnusedObjects.cs
Editor/Processors/AutomaticConfiguration/AutomaticConfigurationProcessor.FindUnusedObjects.cs.meta
Editor/Processors/AutomaticConfiguration/AutomaticConfigurationProcessor.cs
Localization/en.po
Localization/ja.po
Runtime/AutomaticConfiguration.cs

Remove always disabled objects

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/Processors/ClearEndpointPositionProcessor.cs

fix: ClearEndpointPosition only applies to the first PhysBone on the GameObject

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/MergeSkinnedMeshEditor.cs
Editor/Processors/EditSkinnedMeshComponentProcessor.cs
Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
Internal/ErrorReporter/Editor/BuildReport.cs

Weight mismatch warn

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/RemoveMeshByBlendShapeEditor.cs
Localization/en.po
Localization/ja.po

feat(remove-mesh-by-blendshape/editor): auto set blendshape weight

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/OptimizerProcessor.cs
Editor/OptimizerSession.cs
Editor/Processors/EditSkinnedMeshComponentProcessor.cs
Editor/Processors/MergeBoneProcessor.cs
Editor/Processors/MeshInfo2Holder.cs
Editor/Processors/MeshInfo2Holder.cs.meta
Editor/Processors/SkinnedMeshes/EditSkinnedMeshProcessor.cs
Editor/Processors/SkinnedMeshes/FreezeBlendShapeProcessor.cs
Editor/Processors/SkinnedMeshes/InternalAutoFreezeMeaninglessBlendShapeProcessor.cs
Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
Editor/Processors/SkinnedMeshes/MergeToonLitMaterialProcessor.cs
Editor/Processors/SkinnedMeshes/RemoveMeshByBlendShapeProcessor.cs
Editor/Processors/SkinnedMeshes/RemoveMeshInBoxProcessor.cs

Share MeshInfo2 globally

---

CHANGELOG-PRERELEASE.md
Editor/Processors/MergeBoneProcessor.cs
Localization/en.po
Localization/ja.po

fix: MergeBone with uneven scale is supported if all children are merged

---

CHANGELOG-PRERELEASE.md
Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs

Remove unsed Objects Automaticallyでコンタクトが使用されている物にも関わらず、自動で削除されてしまっていたためこのPullRequestのドラフトを書きました
そのコンタクトが、アニメーションで常にオフ、または操作されていないためオフでない場合
ContactSenderは消すべきではなく、ほかのアバターに影響するため専用のような使い方がある、
ContactReceiverは、アニメーションのプロパティなどで、影響するか否かを見つつ消すべきで、アニメーションコントローラーが、そのパラメーターを持っていて、それを使用しているかなどで判断すればよいと思います。
今の状態でパラメーターのパーサーがあるのか私にはわからないので、それの回避策として"EntryPointComponent"を有効にすることで回避していますが、
パラメーターが使用されているかどうかのパーサーがある、または書く意思があるならこの回避策は使うべきではないので、PullRequestはクローズしてください。

ContactBase is accidentally erased by Remove unsed Objects Automatically.

---

CHANGELOG-PRERELEASE.md
Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs

GC parent inactive

---

CHANGELOG-PRERELEASE.md
Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs

chore: automatically merge unnecessary activeness animated GameObject

---

CHANGELOG-PRERELEASE.md
Editor/Processors/SkinnedMeshes/MeshInfo2.cs

Edit by Anatawa12: Fixes #475
----
あるボーン A に PhysBone 等がアタッチされている場合、A にウェイトが乗っているメッシュがすべて削除されていても、関係ないはずの他のメッシュが残っていれば、TraceAndOptimize で A が削除されないようでした。(#475 でしょうか？)
例として
```
- Avatar
- Armature
- けもみみボーン (PhysBone 付き)
- しっぽボーン (PhysBone 付き)
- けもみみメッシュ
- しっぽメッシュ
```
という構成のとき、`しっぽメッシュ` を削除したり常時非アクティブにすると、`しっぽボーン (PhysBone 付き)` は消えてもいいはずだけど残る、という内容です。
影響しそうなところは読んだつもりですが変なことをしていたらすみません。

chore: remove unused bone references just after reading mesh

---

CHANGELOG-PRERELEASE.md
Editor/ObjectMapping/AnimationObjectMapper.cs
Editor/Processors/ApplyObjectMapping.cs

fix: AvatarMask is not mapped

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/OptimizerProcessor.cs
Editor/OptimizerSession.cs
Editor/Processors/OptimizerPlugin.cs
Editor/Processors/OptimizerPlugin.cs.meta
Editor/Utils.cs
Editor/com.anatawa12.avatar-optimizer.editor.asmdef
Internal/ApplyOnPlay/Editor/ApplyOnPlayCallbackRegistry.cs
Internal/ApplyOnPlay/Editor/ApplyOnPlayCaller.cs
Internal/ApplyOnPlay/Editor/ApplyOnPlayConfiguration.cs
Internal/ApplyOnPlay/Editor/IApplyOnPlayCallback.cs
Internal/ApplyOnPlay/Editor/ManualBake.cs
Internal/ApplyOnPlay/Editor/ManualBakeFinallizer.cs
Internal/ApplyOnPlay/Editor/RemoveEditorOnlyOnPlay.cs
Internal/ApplyOnPlay/Editor/com.anatawa12.avatar-optimizer.internal.apply-on-play.editor.asmdef
Internal/ErrorReporter/Editor/ErrorReportingInitializerProcessor.cs
Internal/ErrorReporter/Editor/com.anatawa12.avatar-optimizer.internal.error-reporter.editor.asmdef

This is a draft integration with the ABPF framework, mostly to demonstrate the API. For now, this removes the old Apply On Play logic; not sure if we want to put this back for a transition period, or have it disable itself while ABPF is enabled.
(note: I expect to rename ABPF at some point, consider namespace names/etc to be temporary)

feat: Initial integration with NDMF

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/Processors/SkinnedMeshes/InternalAutoFreezeMeaninglessBlendShapeProcessor.cs
Editor/Processors/SkinnedMeshes/MeshInfo2.cs
Internal/PrefabSafeSet/Runtime/PrefabSafeSet.cs

#520 やってる最中に思いついた差分は小さいけど効果がでかいパフォーマンス改善をpick
40ca051a936421af434dace7729df780ca51cf3e (9b29e0f2685ce09e9a5c5ce837584ed1a6a275dd) がメインの更新。

Performance Improvement

---

.docs/content/_index.ja.md
.docs/content/_index.md

Fixes #524 
発端あたり
https://twitter.com/narazaka/status/1709862000808137137
なんかこんな感じのイメージ
- unitypackageでインストールする人はそもそも色々説明されると混乱する方だと思うので余計な説明は無い方が良いと思うため
- 雑にjaだけやった

docs: VPAIの記述をなくしてunitypackageインストールの説明をシンプルにする

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Internal/PrefabSafeSet/Runtime/PrefabSafeSet.cs
Runtime/AvatarTagComponent.cs
Runtime/ClearEndpointPosition.cs
Runtime/FreezeBlendShape.cs
Runtime/InternalAutoFreezeMeaninglessBlendShape.cs
Runtime/Legacy/Activator.cs
Runtime/Legacy/GlobalActivator.cs
Runtime/MakeChildren.cs
Runtime/MergeBone.cs
Runtime/MergePhysBone.cs
Runtime/MergeSkinnedMesh.cs
Runtime/MergeToonLitMaterial.cs
Runtime/TraceAndOptimize.cs
Runtime/UnusedBonesByReferencesTool.cs
Test~/ComponentSettingsTest.cs

chore: add NotKeyable to every components

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/Migration/PrereleaseStateDetector.cs

> 設定失っていいから、エラー出ないように初期化する機能くれ。
https://fxtwitter.com/status/1712080181761085509
v0.4.xが動かしづらいしまぁ納得は行くので

chore(migration): ignore instead of just close window

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs

Fixes #578 
#579 もやってるけど #520 でやりたい

feat: Satania's Kisetene compatibility

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/APIBackend/ComponentInfos.cs
Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs

Part of #607
- [ParticleSystemForceField](https://docs.unity3d.com/ja/2021.2/ScriptReference/ParticleSystemForceField.html) is `Behaviour` on Unity 2021.3 and higher instead of `Component` and is matched in earlier case
- [UnityEngine.XR.WSA.WorldAnchor](https://docs.unity3d.com/ja/2020.1/ScriptReference/XR.WSA.WorldAnchor.html) is removed on Unity 2020.2 and higher
- [ParticleSystem.CollisionModule.maxPlaneCount](https://docs.unity3d.com/ja/2020.1/ScriptReference/ParticleSystem.CollisionModule-maxPlaneCount.html) is obsolete on Unity 2020.2 and higher

Add Unity version defines

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/com.anatawa12.avatar-optimizer.editor.asmdef
Internal/ErrorReporter/Editor/com.anatawa12.avatar-optimizer.internal.error-reporter.editor.asmdef
Internal/PrefabSafeSet/Runtime/com.anatawa12.avatar-optimizer.internal.prefab-safe-set.asmdef
Internal/PrefabSafeSet/Runtime/generate.ts
Internal/PrefabSafeSet/Runtime/generated.cs
Runtime/com.anatawa12.avatar-optimizer.runtime.asmdef
Test~/com.anatawa12.avatar-optimizer.test.asmdef

Part of #607
Note: I have excluded `.MergePhysBoneEditorModificationUtils.ts` from this PR because I should deal with `MergePhysBoneEditorModificationUtils.cs` simultaneously, and these would be completely ignored by `#if AAO_VRCSDK3_AVATARS` anyway.

Add VRCSDK version defines to asmdefs and code generators

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/Processors/TraceAndOptimize/AnimatorParserDebugWindow.cs

Related Issue: #607
I have to do something with AnimatorParserDebugWindow because it contains `VRCAvatarDescriptor` reference, however I don't know exactly how to deal with it.
This debug tool is useful for AAO users, so it is supposed work without VRCSDK.
`ParserSource.WholeAvatar` should accept something like Animator or Transform for users who wants to edit non-VRChat avatars on projects with VRCSDK. (Warning: this is a breaking change for users with VRCSDK)
This is just a utility debug tool for AAO developers, so it can be safely removed if VRCSDK is not present (this PR).
This debug tool is legacy and would be immediately demolished. 🤯
--- 
Any thoughts?

Disable AnimatorParserDebugWindow if VRCSDK is not present

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Internal/ErrorReporter/Editor/BuildReport.cs
Internal/ErrorReporter/Editor/BuildReportContext.cs

Improve log

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/ExternalLibraryAccessor.cs

fix: DynamicBone does not working with original DynamicBone

---

CHANGELOG-PRERELEASE.md
Editor/Processors/SkinnedMeshes/InternalAutoFreezeMeaninglessBlendShapeProcessor.cs

fix: freeze meaningless may cause `FreezeBlendShape:warning:animation`

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/Processors/SkinnedMeshes/MeshInfo2.cs

I could not find root cause of this bug so I added workaround instead.
I know that
- If I instantiate the generated mesh, broken BlendShapes will be fixed
- If I duplicated the generated mesh with command + d, broken BlendShapes will be fixed
- Even if I moved `AddBlendShapeFrame`s before setting triangles, this will not be fixed
So, as a workaround, instantiate mesh to avoid this bug. I want to test this after dropping Unity 2019.
See https://github.com/anatawa12/AvatarOptimizer/issues/753
Closes #753 for now.

fix: Workaround BlendShape broken bug?

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Internal/PrefabSafeSet/Runtime/PrefabSafeSet.cs

fix error when editing prefab in 2022

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/APIInternal/ComponentInfos.VRCSDK.cs
Editor/AnimatorParsers/AnimatorParser.cs
Editor/OptimizerPlugin.cs
Editor/Processors/ParseAnimator.cs
Editor/Processors/TraceAndOptimize/OptimizePhysBone.cs
Editor/Processors/TraceAndOptimize/OptimizePhysBone.cs.meta
Localization/en.po
Localization/ja.po
Test~/EnumValues.cs
Test~/EnumValues.cs.meta

Warning instead of IndexOutOfBoundsException

---

.github/workflows/gameci.yml
CHANGELOG-PRERELEASE.md
CHANGELOG.md
package.json

Support VRCSDK 3.5.0

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/APIInternal/ComponentInfos.VRM0.cs
Editor/APIInternal/ComponentInfos.VRM1.cs

I don't know whether this branch should be based on `master` or `master-1.6`, so tell me when I need a rebase 😃
- #711 but for VRM0 / VRM1 (Animator component is optional if you don't care animating Humanoid muscles in Unity Editor, which is mostly true if you are just building VRM files with UniVRM)
- VRMSpringBone of VRM0 animates `VRMSpringBone.RootBones`, not children of VRMSpringBone component

Fix VRM component definitions

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/APIInternal/ComponentInfos.VRM0.cs
Editor/APIInternal/ComponentInfos.VRM1.cs
Editor/AnimatorParsers/AnimatorParser.cs
Editor/ObjectMapping/ObjectMappingContext.cs

Fix #809 by marking VRM0 `BlendShapeProxy` as EntryPoint, just like `Animator`.
(VRM1 counterpart, `Vrm10Instance`, is already EntryPoint.)
We should not access `Component.transform` here anyway, because avatar processing is at an intermediate state when FindUnusedObjects is collecting dependencies.
Also I have made an assumption that AvatarOptimizer does not change Material names or remap parameter values, except when MergeToonLitMaterial is used.
(I didn't mark these comments as TODOs because I doubt "tracking material changes" would happen in near future.)

Fix: Treat VRM0 BlendShapeProxy as EntryPoint

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/APIInternal/ComponentInfos.cs
Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs
Editor/Processors/TraceAndOptimize/GCComponentInfo.cs

Fixes #856 in different way.
Reverts #857
Fixes #859

Better activeness animation

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
package.json

VRCSDK with public api is almost required for stable ndmf-vrcsdk compatibility.

chore(deps): upgrade minimum vrcsdk to 3.3.0

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/AnimatorParserV2/AnimatorParser.cs
Editor/Processors/AnimatorOptimizer/AnimOptPassBase.cs

- VRM には AvatarDescriptor はない
- 表情（ VRM0 の BlendShapeClip / VRM1 の Expression ）が操作する対象の BlendShape は普通に重複しうる
- `(target, prop)` が重複すると `ComponentNodeContainer.Add()` が失敗する
- 「複数の表情が同じ BlendShape を操作する」は普通にあり得る
- このパターンの場合、 NodeContainer や PropModeNode を真面目に書いていた可能性がある
- 実際は「一つの表情で同じ BlendShape を複数回操作するデータが作れる」（ VRM は特に重複チェックをしていない）ので、大元で重複チェックすれば良いでしょうという感じになりました

fix: Fix VRM support

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
Localization/en.po
Localization/ja.po

chore(merge-smr): Add error that describes Cloth component is unsupported

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Internal/AnimatorOptimizer/MergeDirectBlendTree.cs

feat(merge-direct-blend-tree): merge non Direct BlendTree

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/AnimatorParserV2/AnimationParser.cs
Editor/AnimatorParserV2/AnimatorParserDebugWindow.cs
Editor/AnimatorParserV2/PropModNode.cs
Editor/Utils/AnimationLocation.cs

fix: AnimationLocation is broken with BlendTree

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/EditModePreview/MeshPreviewController.cs
Editor/EditModePreview/RemoveMeshPreviewController.cs
Editor/Inspector/RemoveMeshByMaskEditor.cs
Editor/MaskTextureEditor.meta
Editor/MaskTextureEditor/Inspector.cs
Editor/MaskTextureEditor/Inspector.cs.meta
Editor/MaskTextureEditor/Shaders.meta
Editor/MaskTextureEditor/Shaders/Fill.shader
Editor/MaskTextureEditor/Shaders/Fill.shader.meta
Editor/MaskTextureEditor/Shaders/Inverse.shader
Editor/MaskTextureEditor/Shaders/Inverse.shader.meta
Editor/MaskTextureEditor/Shaders/Paint.shader
Editor/MaskTextureEditor/Shaders/Paint.shader.meta
Editor/MaskTextureEditor/TexturePainter.cs
Editor/MaskTextureEditor/TexturePainter.cs.meta
Editor/MaskTextureEditor/TextureUndoStack.cs
Editor/MaskTextureEditor/TextureUndoStack.cs.meta
Editor/MaskTextureEditor/UvMapDrawer.cs
Editor/MaskTextureEditor/UvMapDrawer.cs.meta
Editor/MaskTextureEditor/Window.cs
Editor/MaskTextureEditor/Window.cs.meta
Localization/en-us.po
Localization/ja-jp.po

Resolves #1000 です。
Remove Mesh By Mask のマスクテクスチャのフィールドが None の場合は作成ボタンを表示し、そうでない場合は編集ボタンを表示します。
作成ボタンを押すとファイル保存ダイアログが開き、編集ボタンを押すとマスクテクスチャエディターが開きます。
マスクテクスチャエディターには必須かなと思う機能を実装しています。

feat: implement mask texture editor

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/EditModePreview/MeshPreviewController.cs

Fixes #1049 です。
`MeshInfo2.WriteToSkinnedMeshRenderer()` で正しく `AAOGeneratedMeshXXXX` が割り当てられた後、
`MeshPreviewController.Update()` から `StopPreview()` が呼ばれて元アセットのメッシュに戻っているようでした。
本 pullreq ではここで `StopPreview()` を呼ぶようにしていますが、そうしないようコメントにあるのは Play ボタンを押してから Reload Domain/Scene 中にメッシュが完全に消えて見えることへの対策でしょうか？
https://github.com/anatawa12/AvatarOptimizer/blob/06c334e01875be25712a78dac8660336a793e2a5/Editor/EditModePreview/MeshPreviewController.cs#L96-L123
もしそうでしたら、ここで `StopPreview()` を呼ぶだけだと直後の `Update()` で再び `StartPrevew()` されてしまうことが原因なので、`EditorApplication.isPlaying` の判定を `EditorApplication.isPlayingOrWillChangePlaymode` に変更している本 pullreq の対応であれば大丈夫かなと思います。(Reload Domain/Scene がオンの場合 Reload Domain/Scene 中はプレビューが終了した状態が見えます)
そうではない別の事象への対策ということであれば、大丈夫ではないかもしれません。

fix: mesh preview causes empty mesh if reload scene on enter play mode is disabled

---

.docs/content/docs/reference/merge-skinned-mesh/index.ja.md
.docs/content/docs/reference/merge-skinned-mesh/index.md
Localization/en-us.po
Localization/ja-jp.po

fix: #1074 
とりあえず日本語だけ作ったんですけど英語も要りますか?

chore: add more description for MergeSMR

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs

fix: calling AddPathDependency multiple times would lost previous AddPathDependency

---

Localization/en-us.po
Localization/ja-jp.po

chore: mention initially not configured viseme / eyelids

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/APIInternal/ComponentInfos.FinalIK.cs

fix: Dependencies of FinalIK Components referenced by IKExecutionOrder

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Runtime/MergeSkinnedMesh.cs

chore: skipEnablementMismatchedRenderers is now disabled by default

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/EditModePreview/AAORenderFilterBase.cs

AAORenderFilterBase was ignoring renderers where only one component is
attached, when `SupportsMultiple()` is true. This changes it to accept
one or more renderer in this case.

fix: SupportsMultiple components with only one on a renderer are ignored

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/AnimatorParserV2/AnimationParser.cs
Editor/AnimatorParserV2/AnimatorControllerPropModNode.cs
Editor/AnimatorParserV2/AnimatorParser.cs
Editor/AnimatorParserV2/AnimatorParserDebugWindow.cs
Editor/AnimatorParserV2/NodeContainer.cs
Editor/AnimatorParserV2/PropModNode.cs
Editor/AnimatorParserV2/Utilities.cs
Editor/ContextExtensions.cs
Editor/ObjectMapping/PropertyInfo.cs
Editor/Processors/MergePhysBoneProcessor.cs
Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
Editor/Processors/TraceAndOptimize/AutoMergeSkinnedMesh.cs
Editor/Processors/TraceAndOptimize/OptimizeTexture.cs
Editor/Utils/AnimationLocation.cs
Test~/AnimatorParser/TestUtil.cs

Refactors Animator Parser to have different ValueInfo implementation between float and Object
Follow up #1224

refactor: Animator Parser V2.1

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Internal/PrefabSafeSet/Editor/EditorUtil.PrefabModificationOnScene.cs
Internal/PrefabSafeSet/Editor/PrefabSafeSetRuntimeEditorImpl.cs

fix(prefab-safe-set): unncecessary prefab overrides are generated

---

API-Editor/MeshRemovalProvider.cs
API-Editor/UVUsageCompabilityAPI.cs
API-Editor/UVUsageCompabilityAPI.cs.meta
CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/APIInternal/MeshRemovalProviderImpl.cs
Editor/APIInternal/UVUsageCompabilityAPIImpl.cs
Editor/APIInternal/UVUsageCompabilityAPIImpl.cs.meta
Editor/EditSkinnedMeshComponentUtil.cs
Editor/Processors/SkinnedMeshes/EditSkinnedMeshProcessor.cs
Editor/Processors/SkinnedMeshes/EvacuateProcessors.cs
Editor/Processors/SkinnedMeshes/EvacuateProcessors.cs.meta

feat: UVUsageCompabilityAPI for TTT AtlasTexture compatibility

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/Processors/TraceAndOptimize/OptimizeTexture.cs

fix: merge islands incorrectly when one island covers the other

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/NewGameObjectAndAddComponent.cs
Editor/ObjectMapping/ObjectMappingContext.cs

Fixed some compile errors I've found when using AvatarOptimizer in non-VRChat project.

chore: Add conditional compile for VRCSDK API (for 1.8.0-beta.11)

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/Processors/SkinnedMeshes/InternalAutoFreezeMeaninglessBlendShapeProcessor.cs

This saves over 250ms on my main avatar.

perf: optimize InternalAutoFreezeMeaninglessBlendShapeProcessor

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/Processors/TraceAndOptimize/AutoMergeBlendShape.cs

This pass was obtaining the blendshape buffer for each vertex, then processing those buffers.
However, in practice, most vertices share the same buffer; this pass ignored this, and redid
the same work thousands of times as a result.
This reduces processing time from ~370ms to ~22ms on my main avatar.

perf: improve performance of AutoMergeBlendShape

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/Processors/TraceAndOptimize/AutoMergeSkinnedMesh.cs
Test~/Basic/AutoMergeSkinnedMeshTest.cs

The last feature I put in 1.8.
Fix #1284

feat: merge material slot in same mesh

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/Processors/TraceAndOptimize/OptimizeTexture.cs

fix(optimize-texture): InvalidCastException with RenderTexture

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs
Internal/TraceAndOptimizeBase/TraceAndOptimizeProcessor.cs
Runtime/TraceAndOptimize.cs

fix: Errors if objects removed by some component is listed on exclusions of Trace and Optimize

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/EditModePreview/RemoveMeshByMaskRenderFilter.cs

NDMF invokes change checks (Observe callbacks) periodically to check for changes
caused by code that does not properly register change events. While this is time-sliced,
if any single callback takes too long, it can cause poor editor performance.
In AAO, we were checking for changes in mask textures in such a callback; this check retrieved
the `GetPixels32` array, which is an expensive operation which could take dozens of ms in some cases
(particularly since the time-slicing was on a per-object basis, so if the same mask was used by
multiple objects, the overhead adds up).
While NDMF should probably change the time slicing to work on a per-listener basis, and/or add
special handling for `Texture2D`, on the AAO side we can more efficiently perform change checks by\
using unity's built-in …

perf: avoid fetching mask texture data on change check callbacks

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/ObjectMapping/ObjectMappingContext.cs

Two small related fixes around VRM BlendShapes, with self-explanatory commit messages.
- Fixed VRM0 BlendShape / VRM1 Expression target renderer reference/path double mapped.
- FIxed VRM1 default Expressions not processed. (only Custom Expressions are processed)

fix(VRM): Fix VRM BlendShape mapping

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/Processors/TraceAndOptimize/AutoMergeBlendShape.cs

`MergeBlendShapeJob` is missing `[BurstCompile]` attribute, but any other jobs in this library has `[BurstCompile]` attribute.
So this may be not intended.

Add missing `[BurstCompile]` to jobs

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
package.json

Currently, Burst package is referenced indirectly via `com.vrchat.avatars` => `com.vrchat.base` => `com.unity.burst`.
But this library directly uses `[BurstCompile]` attribute.
Referencing Burst package directly will be much robust, and make us be able to use recent Burst package.

Add Burst to dependencies directly

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/APIInternal/ComponentInfos.VRCSDK.cs

According to https://nekolobby.niri.la/notes/a7vq7z0lxj (https://note.com/labo405/n/nac5615af9b0e)
> アバターコライダーはPhysBoneと似た性質を持っており、指定オブジェクトの【親オブジェクトの位置を基準、指定オブジェクトをコライダーの方向】として動作します。

fix: The rotation / position of global physbone collider may be altered

---

CHANGELOG-PRERELEASE.md
CHANGELOG.md
Editor/Processors/TraceAndOptimize/OptimizeTexture.cs

fix: padding used by OptimizeTexture is too small that can be zero pixels.
This can be huge problems with vertex level masking

fix: padding used by OptimizeTexture is too small
